# Generated by Django 5.1.7 on 2025-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationToken',
            fields=[
                ('token', models.UUIDField(primary_key=True, serialize=False)),
                ('revoked', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_hostname', models.CharField(blank=True, default='', max_length=253)),
            ],
        ),
        migrations.CreateModel(
            name='ClipboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=260)),
                ('hostname', models.CharField(blank=True, default='', max_length=253)),
                ('paste_time', models.DateTimeField(blank=True, null=True)),
                ('paste_size', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
