[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "bang-swackhammer"
version = "0.1.0"
description = "welcome to the jam"
dependencies = [
    "django",
    "swackhammer",
]