[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bang-swackhammer"
version = "0.1.0"
description = "welcome to the jam"
dependencies = [
    "django",
    "swackhammer",
]