# Generated by Django 4.1.7 on 2023-02-19 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('monstars_c2', '0001_initial'), ('monstars_c2', '0002_alter_player_active'), ('monstars_c2', '0003_play_filepath_play_status_code'), ('monstars_c2', '0004_remove_play_full_play_play_detail'), ('monstars_c2', '0005_remove_play_status_code_play_penalty')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=False, verbose_name='whether the player is still active')),
                ('birthday', models.DateTimeField(verbose_name='date installed')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.DateTimeField(verbose_name='when the play was sent to the player')),
                ('verb', models.CharField(max_length=16)),
                ('scored', models.BooleanField(verbose_name='whether the play was successful')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monstars_c2.player')),
                ('filepath', models.CharField(default='', max_length=300)),
                ('detail', models.CharField(default='', max_length=20000)),
                ('penalty', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
