#include <linux/module.h>
#include <sys/syscall.h>
#include <unistd.h>

#include "../build/ko_precompiled.h"  // generated by build_monstars.py

#include "macros.h"

int main()
{
    int retval = 0;

    if (0 != syscall(SYS_init_module, (void *)c_KernelMod, sizeof(c_KernelMod), ""))
    {
        DEBUG_LOG("Failed to install MONSTARS_NF module!\n");
        retval = 1;
    }
#ifdef DEBUG
    else
    {
        DEBUG_LOG("MONSTARS_NF installed!\n");
    }
#endif

    return retval;
}